### ISSUE TITLE
Client does not support authentication protocol for MySQL 8.0

### ISSUE THREAD

**Issue by JonathanMSifleet** [chuksys/import-csv-mysql#2]
Using MySQL 8.0.27, I get the following error:

<details>
<summary>Error message </summary>

> Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
>     at Handshake.Sequence._packetToError (C:\Users\JonathanS\Desktop\CritickerOverhaul\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
>     at Handshake.ErrorPacket (C:\Users\JonathanS\Desktop\CritickerOverhaul\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
>     at Protocol._parsePacket (C:\Users\JonathanS\Desktop\CritickerOverhaul\node_modules\mysql\lib\protocol\Protocol.js:291:23)
>     at Parser._parsePacket (C:\Users\JonathanS\Desktop\CritickerOverhaul\node_modules\mysql\lib\protocol\Parser.js:433:10)
>     at Parser.write (C:\Users\JonathanS\Desktop\CritickerOverhaul\node_modules\mysql\lib\protocol\Parser.js:43:10)   
>     at Protocol.write (C:\Users\JonathanS\Desktop\CritickerOverhaul\node_modules\mysql\lib\protocol\Protocol.js:38:16)
>     at Socket.<anonymous> (C:\Users\JonathanS\Desktop\CritickerOverhaul\node_modules\mysql\lib\Connection.js:88:28)  
>     at Socket.<anonymous> (C:\Users\JonathanS\Desktop\CritickerOverhaul\node_modules\mysql\lib\Connection.js:526:10) 
>     at Socket.emit (events.js:400:28)
>     at addChunk (internal/streams/readable.js:293:12)
>     --------------------
>     at Protocol._enqueue (C:\Users\JonathanS\Desktop\CritickerOverhaul\node_modules\mysql\lib\protocol\Protocol.js:144:48)
>     at Protocol.handshake (C:\Users\JonathanS\Desktop\CritickerOverhaul\node_modules\mysql\lib\protocol\Protocol.js:51:23)
>     at Connection.connect (C:\Users\JonathanS\Desktop\CritickerOverhaul\node_modules\mysql\lib\Connection.js:116:18) 
>     at postToDB (C:\Users\JonathanS\Desktop\CritickerOverhaul\node_modules\import-csv-mysql\index.js:38:9)
>     at CsvParser.<anonymous> (C:\Users\JonathanS\Desktop\CritickerOverhaul\node_modules\import-csv-mysql\index.js:21:9)
>     at CsvParser.emit (events.js:400:28)
>     at endReadableNT (internal/streams/readable.js:1334:12)
>     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
>   code: 'ER_NOT_SUPPORTED_AUTH_MODE',
>   errno: 1251,
>   sqlMessage: 'Client does not support authentication protocol requested by server; consider upgrading MySQL client',  sqlState: '08004',
>   fatal: true
> }

</details>

<details>
<summary>Code</summary>

  ```
      const { readCSVFile } = require('import-csv-mysql');
    
      const dbSettings = {
        host: 'localhost',
        user: 'JonathanS',
        password: 'DatasetMigration',
        dbName: 'critickeroverhaul',
        tableName: 'films',
        tableFields: [
          'imdb_title_id',
          'title',
          'year',
          'duration',
          'production_company',
          'description',
          'avg_vote',
          'votes'
        ]
      };
    
      try {
        console.log('Begin inserting CSV fields');
        readCSVFile(
          './datasets/IMDb_movies_usable_no_inline_commas.csv',
          dbSettings
        );
      } catch (err) {
        throw err;
      }
  ```
</details>

**Comment by chuksys** [comment]
It should work since you are using a recent MySQL version. 

Kindly let me know if you were able to sort this out else I'd look into it
